[package]
name = "rust-explore"
version = "0.1.0"
authors = ["David Peklak <dpeklak@gmail.com>"]

[lib]
name = "explore"
path = "src/explore/lib.rs"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[dependencies]
byteorder = "1"
hyper = "0.10"
